import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header/Header";
import Footer from "@/components/shared/footer/Footer";
import StoreProvider from "./StoreProvider";
import DesktopSearchBar from "@/components/shared/header/searchBar/DesktopSearchBar";
import AuthProvider from "./authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <StoreProvider>
          <Header />
          <main className="">{children}</main>
          <Footer />
        </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
